name: SimpleCheckServer
main: SimpleCheckServer\Main
version: 1.1Dev
api: 1.12.0
load: STARTUP
author: MineBuilderFR

commands:

  checkserver:
    description: Base CheckServer command
    permission: checkserver.op

permissions:
    checkserver.op:
      description: Allow To Execute Command Reserved /checkserver
      default: op 